### ISSUE TITLE
Idiomatic Conversation

### ISSUE THREAD

**Issue by requaos** [jhillyerd/enmime#126]
What I did:
Contributed code

What I expected:
Everything to be perfect

What I got:
Self-conscious about the code I contributed

Release or branch I am using:
N/A

[Dave Cheney Practical-Go Guide](https://dave.cheney.net/practical-go/presentations/qcon-china.html)
[Golang Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments)

**Comment by requaos** [comment]
I just wanted to open this conversation, since there have been some head-scratchers about how idiomatic this or that pattern is, as well as time lost on what to name a receiver variable.

**Comment by jhillyerd** [comment]
My general goals with enmime PRs and reviews:

1. Consistent: new enmime code should look similar to existing enmime code.
2. Idiomatic: enmime code should look similar to what is in the Go std library, with some exceptions.
3. Approachable: enmime shouldn't be too difficult to understand for a new contributor.
4. Maintainable: we should be able to refactor and be comfortable that our unit tests will surface problems.

I'll go into a bit more detail about those in other comments, but I think I should also frame where I'm coming from:  Code reviews at Google can be brutal and often full of little nit-picks.  After going through a few of them, I've learned to not take it personally, and think of it as a team effort.

Similarly, I welcome feedback when my review comments are off the mark.  Correct code is more important than me being right. :)

Also:

- I am typically not running the code, or even looking at it in an IDE, I just use the GitHub UI.  It's entirely possible I get confused about something; don't hesitate to push back if that seems to be the case.
- I'm not paid to work on enmime, so I do reviews in spare time, but also try to review PRs in less than a week; so they may be rushed.
- enmime was started in 2012, and my level of experience and opinions have changed since.  I've done some refactoring, but there may be some cruft left in places (violating 1 above).

**Comment by jhillyerd** [comment]
From that first Cheney Go guide:

- Short variable names work well when the distance between their declaration and last use is short.
- Long variable names need to justify themselves; the longer they are the more value they need to provide. Lengthy bureaucratic names carry a low amount of signal compared to their weight on the page.
- Don’t include the name of your type in the name of your variable.
- Constants should describe the value they hold, not how that value is used.
- Prefer single letter variables for loops and branches, single words for parameters and return values, multiple words for functions and package level declarations
- Prefer single words for methods, interfaces, and packages.
- Remember that the name of a package is part of the name the caller uses to to refer to it, so make use of that.

I agree with most of that, adding that we see some conventions in the Go stdlib (from memory):
- `s` for input string when the function is short and simple
- `c`, `r` for character or rune when looping over something
- `i`, `j` for loop indices
- `p` (probably for pointer) when re-slicing a string repeatedly during a parse

**Comment by jhillyerd** [comment]
(copied from one of the PRs)

We need to settle on a common set of variable names for parsing mime types. Glancing at the RFC, I propose:

* `param` for an entire single parameter definition string (ie, pname + `=` + pvalue)
* `params` for a slice of `param` values above
* `pname` for parameter name
* `pvalue` for parameter value

We could also use:

* `hname` for header name
* `hvalue` for the header value

**Comment by jhillyerd** [comment]
I also try to wrap at 100 columns; as 80 feels constricted but higher makes it hard to view a side-by-side diff.

**Comment by jhillyerd** [comment]
Variable initialization: Probably more of a personal preference (and being bitten by NPEs in Java), than Go idoms.  Be explicit about initialization values, despite Go always initializing variables (I'd make an exception for structs.)

This makes code easier to visually scan:

Good:
```go
flag := false
```

Bad as I have to think about what the default bool value is when scanning:
```go
var flag bool
```

Prefer the common value as initializer over having two branches:

Good:
```go
// foo is usually 10.
foo := 10
if 0 > 1 {
  foo = 20
}
```

Annoying to me:
```go
var foo int
if 0 > 1 {
  foo = 20
} else {
  foo = 10
}
```
