### ISSUE TITLE
RFCs Supported

### ISSUE THREAD

**Issue by sethgrid** [jhillyerd/enmime#33]
It would be be nice if you could list what RFCs this library supports :)

**Comment by jhillyerd** [comment]
I followed a couple (early) RFCs when initially implementing the library, but it has since been refactored and received a number of pull requests - so the unit tests are the best documentation of it's capabilities.

Enmime was created primarily to support Inbucket, although I'd like it to be as complete as possible.  I'm not paid to work on either project, so they don't get a great deal of attention.

If someone is interested in building tests to exercise entire RFCs, I'm happy to accept PRs.  But it's not something I plan to spend time on.
