### ISSUE TITLE
Decoding issue (Used in Mailpit)

### ISSUE THREAD

**Issue by D3strukt0r** [jhillyerd/enmime#340]
A tool we use at work, uses your library. It's creator forwarded me to your library, so here I am. The original issue is at https://github.com/axllent/mailpit/issues/348

@axllent also commented a go example for smth, you might wanna check it out.

Basically, an email shown by this tool formats the text with wrong characters.

Here are a working case (any length shorter or equal to this will work) 

[example-works.eml.txt](https://github.com/user-attachments/files/16622607/example-works.eml.txt)

![image](https://github.com/user-attachments/assets/35bd926a-855e-4ea9-bfea-0ab3667b474c)

And an example where anything longer or equal to this length (not sure if this is actually true) will break

[example-broken.eml.txt](https://github.com/user-attachments/files/16622612/example-broken.eml.txt)

![image](https://github.com/user-attachments/assets/d2694495-13ec-42c1-a095-bf60cf208313)

when being sent to any other mailcatcher software or opening in MS Outlook, it is displayed correctly

![image](https://github.com/user-attachments/assets/55af297d-6c4f-41ee-8178-76437aef052d)

I hope this can help you identify the issue :)

**Comment by axllent** [comment]
I have finally worked out why and where it is happening ([for reference](https://github.com/jhillyerd/enmime/blob/main/part.go#L213-L229)), I just don't understand the reasoning. 

Basically the logic here states that the character set for content should be "auto detected" from the content itself if, among other things, the length of the content is greater than 100 characters. This 100 characters happened to be the difference in your working and broken examples.

I'm not sure I agree with this logic, because, as far as I'm concerned, if an email part claims it is UTF-8-encoded then that is what should be used. There may be good reason the enmime relies more on auto-detection than what is stated in the email itself. @jhillyerd - are you able to shed any light on why this is the case?

**Comment by jhillyerd** [comment]
Thanks for looking into this, I suspected that chardet would be the cause but didn't have time right now to dig into it.  #81 provides the original reasoning (and #132 sets the 100 rune threshold) -- essentially here is a *lot* of poorly encoded email out there, and enmime get used often in systems parsing mail archives and the like where the source material cannot be fixed.  Spam is also often intentionally encoded poorly to try and bypass filters.

Now that we support [decoding options](https://pkg.go.dev/github.com/jhillyerd/enmime#Option), it would probably make sense to allow the character set detection to be disabled entirely, and the 100 character threshold to be modified.

**Comment by axllent** [comment]
Thanks for the response @jhillyerd - that makes a lot of sense. Ironically in my case (ie: Mailpit) I actually want it to decode with the supplied encoding (assuming there is one) to help identify issues (ie: the point of Mailpit). Detection would probably be helpful if none was provided, but that is really secondary. If an email says a part os `ISO-8859-1` then I really want to decode it as that, regardless if the detection is 100% sure it's not.

What would you suggest is my best approach?
1. Wait for an update in enmime in which I can possibly set this via the decoding options, or
2. Create a "Mailpit fork" specifically to handle this

I'd rather not fork if I don't have to, but I also realise that your use-case for enmime differs from mine (youre doing your nest to decode things despite that the encoding tells you, whereas I want it to break when it's incorrect) ;-) Open to suggestions / thoughts.
