### ISSUE TITLE
Should we make enmime more  fault-tolerant？

### ISSUE THREAD

**Issue by leibiao** [jhillyerd/enmime#46]
Recently I made a little test using following content with **enmime**
```
Content-Type: multipart/mixed; boundary="Enmime-Test-100"

--Enmime-Test-100
Content-Transfer-Encoding: base64
Content-Type: text/html; charset=utf-8

PGgxPlRlc3QhPC9oMT4K
--Enmime-Test-100
Content-Transfer-Encoding: base64
Content-Type: application/octet-stream; name="test.txt.gz"; charset="us-ascii"
Content-Disposition: attachment; filename=test.txt.gz

H4sICG2/PFoAA3Rlc3QudHh0ACtJLS7hAgDGNbk7BQAAAA==

--Enmime-Test-100--
```
As you can see, when I append a '=' to the html part's content `PGgxPlRlc3QhPC9oMT4K`, it's a malformed base64 encoded string and will abort the work of **enmime**.Ok, I saved this modified content and opened it with macOS's Mail app, I also can get the correct attachment though the html part is displayed incorrecly.
Another example is, when I insert a speciall byte into fourth from the bottom of attachment's content  like follows.
```
41 3D 3D    A==     ------->     11 41 3D 3D     .A==
```
Obviously, it is also a malformed base64 encoded string, but it can be extracted with **enmime** .The key problem is the extracted file can't be uncompressed while extracted with another tools like  Mail.app,Thunderbird and python's built-in package can be uncompressed correctly.

**Comment by jhillyerd** [comment]
Yes, my goal for enmime is to make it parse most reasonable emails, and aggregate the parsing errors so that tools like [inbucket](http://www.inbucket.org/) can display them; you can see this work started in #1 

We even have a cleaner in base64.go that attempts to work around some bugs I found with Go's own base64 decoder when first building enmine.  It was never wired into the error aggregation system.

It would make sense to add an `Errors` slice to the `base64Cleaner` struct, and an `errorMalformedBase64` const to `errors.go`, plus whatever other plumbing is required to surface those errors to the consumer.
